### ISSUE TITLE
trying to vote results in a 500 error page

### ISSUE THREAD

**Issue by mer2329** [ServerListPlus/issues#31]
im trying to vote for modrealms (https://moddedminecraft.com/servers/4-ModRealms) but when i type my username (its correct as it works on other sites) in and submit i get sent to https://moddedminecraft.com/internal-server-error

**Comment by Brend-Smits** [comment]
Oh no! This is not good! Thank you for making us aware.
We will look into this and fix it as soon as possible.

Thanks again!

**Comment by mer2329** [comment]
its workign now. thanks

**Comment by mer2329** [comment]
hello. this has reared its ugly head again. this time its effecting the whole site. even the homepage.

**Comment by MaxKorlaar** [comment]
That's not good! I can confirm the issue that you're having and will ask @Brend-Smits to take a look for you.

**Comment by Brend-Smits** [comment]
Thanks all for the info.. I'm taking a lot as we speak!

**Comment by Brend-Smits** [comment]
I spend more hours on this than anticipated. There were some storage issues that caused the database to be corrupted. Everything is now restored and back functional. I will spend additional resources to prevent this from happening in the future.

Thank you for your patience and for reporting!
